FROM debian:bookworm-slim
ARG TARGETPLATFORM
RUN apt-get update && apt-get install -y --no-install-recommends ca-certificates && rm -rf /var/lib/apt/lists/*
COPY ${TARGETPLATFORM}/httpbin /httpbin
EXPOSE 8088
ENTRYPOINT ["/httpbin"]
CMD ["-port", "8088"]
